name: Validate

on:
  pull_request:
    branches:
      - 'main'

jobs:
  # Check
  validate:
    name: Validate
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - run: cd validate
      - run: npm install --save=false
      - run: node validate.js
